schema:
 - https://api-eu-central-1.graphcms.com/v2/ckjpnzxc4la3y01z1fplqd8oj/master:
    headers:
        Authorization: Bearer ${FRIEDL_RECIPES_TOKEN}

documents: '**/*.graphql'

plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
